baseURL = "https://porrizx.cc/"
# [en, zh-cn, fr, ...] è®¾ç½®é»˜è®¤çš„è¯­è¨€
defaultContentLanguage = "zh-cn"
# ç½‘ç«™è¯­è¨€, ä»…åœ¨è¿™é‡Œ CN å¤§å†™
languageCode = "zh-CN"
# æ˜¯å¦åŒ…æ‹¬ä¸­æ—¥éŸ©æ–‡å­—
hasCJKLanguage = true
# ç½‘ç«™æ ‡é¢˜
title = "porrizxçš„ç¯ç«"

# æ›´æ”¹ä½¿ç”¨ Hugo æ„å»ºç½‘ç«™æ—¶ä½¿ç”¨çš„é»˜è®¤ä¸»é¢˜
theme = "FixIt"

enableEmoji = true

[params]
#  FixIt ä¸»é¢˜ç‰ˆæœ¬
version = "0.2.18"
# ç½‘ç«™æè¿°
description = "porrizxçš„ç¯ç«,hugo,æ‘„å½±,å»¶æ—¶æ‘„å½±,æ ‘è“æ´¾,ä¸²å£,è“ç‰™,vsftpd,çŒ«çŒ«,opencv,yolo"
# ç½‘ç«™å…³é”®è¯
keywords = ["porrizxçš„ç¯ç«", "hugo", "æ‘„å½±", "å»¶æ—¶æ‘„å½±", "æ ‘è“æ´¾", "ä¸²å£", "è“ç‰™", "vsftpd", "çŒ«çŒ«", "opencv", "yolo"]
# ç½‘ç«™é»˜è®¤ä¸»é¢˜æ ·å¼ ("light", "dark", "auto")
defaultTheme = "auto"
# å…¬å…± git ä»“åº“è·¯å¾„ï¼Œä»…åœ¨ enableGitInfo è®¾ä¸º true æ—¶æœ‰æ•ˆ
gitRepo = "https://github.com/porrizxx"
#  å“ªç§å“ˆå¸Œå‡½æ•°ç”¨æ¥ SRI, ä¸ºç©ºæ—¶è¡¨ç¤ºä¸ä½¿ç”¨ SRI
# ("sha256", "sha384", "sha512", "md5")
fingerprint = ""
#  æ—¥æœŸæ ¼å¼
dateFormat = "2006-01-02"
# ç½‘ç«™å›¾ç‰‡, ç”¨äº Open Graph å’Œ Twitter Cards
images = ["/img/logo.png"]
#  å¼€å¯ PWA æ”¯æŒ
enablePWA = true
[params.busuanzi]
enable = true

#  åº”ç”¨å›¾æ ‡é…ç½®
[params.app]
# å½“æ·»åŠ åˆ° iOS ä¸»å±å¹•æˆ–è€… Android å¯åŠ¨å™¨æ—¶çš„æ ‡é¢˜, è¦†ç›–é»˜è®¤æ ‡é¢˜
title = "porrizxçš„ç¯ç«"
# æ˜¯å¦éšè—ç½‘ç«™å›¾æ ‡èµ„æºé“¾æ¥
noFavicon = false
# æ›´ç°ä»£çš„ SVG ç½‘ç«™å›¾æ ‡, å¯æ›¿ä»£æ—§çš„ .png å’Œ .ico æ–‡ä»¶
svgFavicon = "/img/logo.svg"
# Android æµè§ˆå™¨ä¸»é¢˜è‰²
themeColor = "#ffffff"
# Safari å›¾æ ‡é¢œè‰²
iconColor = "#5bbad5"
# Windows v8-10ç£è´´é¢œè‰²
tileColor = "#da532c"

#  æœç´¢é…ç½®
[params.search]
enable = true
# æœç´¢å¼•æ“çš„ç±»å‹ ["lunr", "algolia", "fuse"]
type = "lunr"
# æ–‡ç« å†…å®¹æœ€é•¿ç´¢å¼•é•¿åº¦
contentLength = 4000
# æœç´¢æ¡†çš„å ä½æç¤ºè¯­
placeholder = ""
#  æœ€å¤§ç»“æœæ•°ç›®
maxResultLength = 10
#  ç»“æœå†…å®¹ç‰‡æ®µé•¿åº¦
snippetLength = 50
#  æœç´¢ç»“æœä¸­é«˜äº®éƒ¨åˆ†çš„ HTML æ ‡ç­¾
highlightTag = "em"
#  æ˜¯å¦åœ¨æœç´¢ç´¢å¼•ä¸­ä½¿ç”¨åŸºäº baseURL çš„ç»å¯¹è·¯å¾„
absoluteURL = false
[params.search.algolia]
index = ""
appID = ""
searchKey = ""
[params.search.fuse]
#  https://fusejs.io/api/options.html
isCaseSensitive = false
minMatchCharLength = 2
findAllMatches = false
location = 0
threshold = 0.3
distance = 100
ignoreLocation = false
useExtendedSearch = false
ignoreFieldNorm = false

# é¡µé¢å¤´éƒ¨å¯¼èˆªæ é…ç½®
[params.header]
#  æ¡Œé¢ç«¯å¯¼èˆªæ æ¨¡å¼ ["sticky", "normal", "auto"]
desktopMode = "sticky"
#  ç§»åŠ¨ç«¯å¯¼èˆªæ æ¨¡å¼ ["sticky", "normal", "auto"]
mobileMode = "auto"
#  é¡µé¢å¤´éƒ¨å¯¼èˆªæ æ ‡é¢˜é…ç½®
[params.header.title]
# LOGO çš„ URL
logo = ""
# æ ‡é¢˜åç§°
name = "cd /home/ğŸ˜"
# ä½ å¯ä»¥åœ¨åç§° (å…è®¸ HTML æ ¼å¼) ä¹‹å‰æ·»åŠ å…¶ä»–ä¿¡æ¯, ä¾‹å¦‚å›¾æ ‡
pre = "># "
# ä½ å¯ä»¥åœ¨åç§° (å…è®¸ HTML æ ¼å¼) ä¹‹åæ·»åŠ å…¶ä»–ä¿¡æ¯, ä¾‹å¦‚å›¾æ ‡
post = ""
#  æ˜¯å¦ä¸ºæ ‡é¢˜æ˜¾ç¤ºæ‰“å­—æœºåŠ¨ç”»
typeit = true

# é¡µé¢åº•éƒ¨ä¿¡æ¯é…ç½®
[params.footer]
enable = true
#  è‡ªå®šä¹‰å†…å®¹ (æ”¯æŒ HTML æ ¼å¼)
custom = ''
#  æ˜¯å¦æ˜¾ç¤º Hugo å’Œä¸»é¢˜ä¿¡æ¯
hugo = false
#  æ˜¯å¦æ˜¾ç¤ºç‰ˆæƒä¿¡æ¯
copyright = true
#  æ˜¯å¦æ˜¾ç¤ºä½œè€…
author = true
# ç½‘ç«™åˆ›ç«‹å¹´ä»½
since = 2021
#  æ˜¯å¦æ˜¾ç¤ºç½‘ç«™å†…å®¹æ€»å­—æ•°
wordCount = true
#  å…¬ç½‘å®‰å¤‡ä¿¡æ¯ï¼Œä»…åœ¨ä¸­å›½ä½¿ç”¨ï¼ˆæ”¯æŒ HTML æ ¼å¼ï¼‰
gov = ""
# ICP å¤‡æ¡ˆä¿¡æ¯ï¼Œä»…åœ¨ä¸­å›½ä½¿ç”¨ (æ”¯æŒ HTML æ ¼å¼)
icp = ""
# è®¸å¯åè®®ä¿¡æ¯ (æ”¯æŒ HTML æ ¼å¼)
license = ''
#  é¡µé¢åº•éƒ¨è¡Œæ’åºï¼Œå¯é€‰å€¼ï¼š["first", 0, 1, 2, 3, 4, 5, "last"]
[params.footer.order]
powered = 0
copyright = 0
statistics = 0
visitor = 0
beian = 0
#  Section (æ‰€æœ‰æ–‡ç« ) é¡µé¢é…ç½®
[params.section]
# section é¡µé¢æ¯é¡µæ˜¾ç¤ºæ–‡ç« æ•°é‡
paginate = 20
# æ—¥æœŸæ ¼å¼ (æœˆå’Œæ—¥)
dateFormat = "01-02"
# RSS æ–‡ç« æ•°ç›®
rss = 10
#  æœ€è¿‘æ›´æ–°æ–‡ç« è®¾ç½®
[params.section.recentlyUpdated]
enable = false
rss = false
days = 30
maxCount = 10

#  List (ç›®å½•æˆ–æ ‡ç­¾) é¡µé¢é…ç½®
[params.list]
# list é¡µé¢æ¯é¡µæ˜¾ç¤ºæ–‡ç« æ•°é‡
paginate = 20
# æ—¥æœŸæ ¼å¼ (æœˆå’Œæ—¥)
dateFormat = "01-02"
# RSS æ–‡ç« æ•°ç›®
rss = 10

#  æ ‡ç­¾äº‘é…ç½®
[params.tagcloud]
enable = false
min = 14 # æœ€å°å­—ä½“å¤§å°ï¼Œå•ä½ï¼špx
max = 32 # æœ€å¤§å­—ä½“å¤§å°ï¼Œå•ä½ï¼špx
peakCount = 10 # æ¯ä¸ªæ ‡ç­¾çš„æœ€å¤§æ–‡ç« æ•°
orderby = "name" # æ ‡ç­¾æ’åºæ–¹å¼ï¼Œå¯é€‰å€¼ï¼š["name", "count"]

# ä¸»é¡µé…ç½®
[params.home]
#  RSS æ–‡ç« æ•°ç›®
rss = 10
# ä¸»é¡µä¸ªäººä¿¡æ¯
[params.home.profile]
enable = false
# Gravatar é‚®ç®±ï¼Œç”¨äºä¼˜å…ˆåœ¨ä¸»é¡µæ˜¾ç¤ºçš„å¤´åƒ
gravatarEmail = "1119864054@qq.com"
# ä¸»é¡µæ˜¾ç¤ºå¤´åƒçš„ URL
avatarURL = ""
#  ä¸»é¡µæ˜¾ç¤ºçš„ç½‘ç«™æ ‡é¢˜ (æ”¯æŒ HTML æ ¼å¼)
title = "porrizx"
# ä¸»é¡µæ˜¾ç¤ºçš„ç½‘ç«™å‰¯æ ‡é¢˜
subtitle = "TEST"
# æ˜¯å¦ä¸ºå‰¯æ ‡é¢˜æ˜¾ç¤ºæ‰“å­—æœºåŠ¨ç”»
typeit = true
# æ˜¯å¦æ˜¾ç¤ºç¤¾äº¤è´¦å·
social = true
#  å…è´£å£°æ˜ (æ”¯æŒ HTML æ ¼å¼)
disclaimer = ""
# ä¸»é¡µæ–‡ç« åˆ—è¡¨
[params.home.posts]
enable = true
# ä¸»é¡µæ¯é¡µæ˜¾ç¤ºæ–‡ç« æ•°é‡
paginate = 20
#  è¢« params.page ä¸­çš„ hiddenFromHomePage æ›¿ä»£
# å½“ä½ æ²¡æœ‰åœ¨æ–‡ç« å‰ç½®å‚æ•°ä¸­è®¾ç½® "hiddenFromHomePage" æ—¶çš„é»˜è®¤è¡Œä¸º
defaultHiddenFromHomePage = false

# ä½œè€…çš„ç¤¾äº¤ä¿¡æ¯è®¾ç½®
[params.social]
GitHub = "https://github.com/porrizxx"
Linkedin = ""
Twitter = ""
Instagram = ""
Facebook = ""
Telegram = ""
Medium = ""
Gitlab = ""
Youtubelegacy = ""
Youtubecustom = ""
Youtubechannel = ""
Tumblr = ""
Quora = ""
Keybase = ""
Pinterest = ""
Reddit = ""
Codepen = ""
FreeCodeCamp = ""
Bitbucket = ""
Stackoverflow = ""
Weibo = ""
Odnoklassniki = ""
VK = ""
Flickr = ""
Xing = ""
Snapchat = ""
Soundcloud = ""
Spotify = ""
Bandcamp = ""
Paypal = ""
Fivehundredpx = ""
Mix = ""
Goodreads = ""
Lastfm = ""
Foursquare = ""
Hackernews = ""
Kickstarter = ""
Patreon = ""
Steam = ""
Twitch = ""
Strava = ""
Skype = ""
Whatsapp = ""
Zhihu = ""
Douban = ""
Angellist = ""
Slidershare = ""
Jsfiddle = ""
Deviantart = ""
Behance = ""
Dribbble = ""
Wordpress = ""
Vine = ""
Googlescholar = ""
Researchgate = ""
Mastodon = ""
Thingiverse = ""
Devto = ""
Gitea = ""
XMPP = ""
Matrix = ""
Bilibili = ""
Email = "1119864054@qq.com"
RSS = true

#  æ–‡ç« é¡µé¢é…ç½®
[params.page]
#  æ˜¯å¦åœ¨ä¸»é¡µéšè—ä¸€ç¯‡æ–‡ç« 
hiddenFromHomePage = false
#  æ˜¯å¦åœ¨æœç´¢ç»“æœä¸­éšè—ä¸€ç¯‡æ–‡ç« 
hiddenFromSearch = false
#  æ˜¯å¦ä½¿ç”¨ twemoji
twemoji = true
# æ˜¯å¦ä½¿ç”¨ lightgallery
lightgallery = false
#  æ˜¯å¦ä½¿ç”¨ ruby æ‰©å±•è¯­æ³•
ruby = true
#  æ˜¯å¦ä½¿ç”¨ fraction æ‰©å±•è¯­æ³•
fraction = true
#  æ˜¯å¦ä½¿ç”¨ fontawesome æ‰©å±•è¯­æ³•
fontawesome = true
# æ˜¯å¦åœ¨æ–‡ç« é¡µé¢æ˜¾ç¤ºåŸå§‹ Markdown æ–‡æ¡£é“¾æ¥
linkToMarkdown = true
#  æ˜¯å¦åœ¨ RSS ä¸­æ˜¾ç¤ºå…¨æ–‡å†…å®¹
rssFullText = false
#  é¡µé¢æ ·å¼ ["narrow", "normal", "wide", ...]
pageStyle = "normal"
#   å¼ºåˆ¶ä½¿ç”¨ Gravatar ä½œä¸ºä½œè€…å¤´åƒ
# gravatarForce = true
#  å¼€å¯è‡ªåŠ¨ä¹¦ç­¾æ”¯æŒ
# å¦‚æœä¸º trueï¼Œåˆ™åœ¨å…³é—­é¡µé¢æ—¶ä¿å­˜é˜…è¯»è¿›åº¦
autoBookmark = false
#  æ˜¯å¦ä½¿ç”¨ å­—æ•°ç»Ÿè®¡
wordCount = true
#  æ˜¯å¦ä½¿ç”¨ é¢„è®¡é˜…è¯»
readingTime = true
#  æ–‡ç« ç»“æŸæ ‡å¿—
endFlag = ""
#  æ˜¯å¦å¼€å¯å³æ—¶é¡µé¢
instantPage = false

#  è½¬è½½é…ç½®
[params.page.repost]
enable = false
url = ""
#  ç›®å½•é…ç½®
[params.page.toc]
# æ˜¯å¦ä½¿ç”¨ç›®å½•
enable = true
#  æ˜¯å¦ä¿æŒä½¿ç”¨æ–‡ç« å‰é¢çš„é™æ€ç›®å½•
keepStatic = false
# æ˜¯å¦ä½¿ä¾§è¾¹ç›®å½•è‡ªåŠ¨æŠ˜å å±•å¼€
auto = false
#  ç›®å½•ä½ç½® ["left", "right"]
position = "right"
#  åœ¨æ–‡ç« å¼€å¤´æ˜¾ç¤ºæç¤ºä¿¡æ¯ï¼Œæé†’è¯»è€…æ–‡ç« å†…å®¹å¯èƒ½è¿‡æ—¶
[params.page.expirationReminder]
enable = false
# å¦‚æœæ–‡ç« æœ€åæ›´æ–°äºè¿™å¤©æ•°ä¹‹å‰ï¼Œæ˜¾ç¤ºæé†’
reminder = 90
# å¦‚æœæ–‡ç« æœ€åæ›´æ–°äºè¿™å¤©æ•°ä¹‹å‰ï¼Œæ˜¾ç¤ºè­¦å‘Š
warning = 180
# å¦‚æœæ–‡ç« åˆ°æœŸæ˜¯å¦å…³é—­è¯„è®º
closeComment = false
#  ä»£ç é…ç½®
[params.page.code]
# æ˜¯å¦æ˜¾ç¤ºä»£ç å—çš„å¤åˆ¶æŒ‰é’®
copy = true
# é»˜è®¤å±•å¼€æ˜¾ç¤ºçš„ä»£ç è¡Œæ•°
maxShownLines = 1000
#  KaTeX æ•°å­¦å…¬å¼
[params.page.math]
enable = true
# é»˜è®¤å—å®šç•Œç¬¦æ˜¯ $$ ... $$ å’Œ \\[ ... \\]
blockLeftDelimiter = ""
blockRightDelimiter = ""
# é»˜è®¤è¡Œå†…å®šç•Œç¬¦æ˜¯ $ ... $ å’Œ \\( ... \\)
inlineLeftDelimiter = ""
inlineRightDelimiter = ""
# KaTeX æ’ä»¶ copy_tex
copyTex = true
# KaTeX æ’ä»¶ mhchem
mhchem = true
#  Mapbox GL JS é…ç½®
[params.page.mapbox]
# Mapbox GL JS çš„ access token
accessToken = ""
# æµ…è‰²ä¸»é¢˜çš„åœ°å›¾æ ·å¼
lightStyle = "mapbox://styles/mapbox/light-v9"
# æ·±è‰²ä¸»é¢˜çš„åœ°å›¾æ ·å¼
darkStyle = "mapbox://styles/mapbox/dark-v9"
# æ˜¯å¦æ·»åŠ  NavigationControl
navigation = true
# æ˜¯å¦æ·»åŠ  GeolocateControl
geolocate = true
# æ˜¯å¦æ·»åŠ  ScaleControl
scale = true
# æ˜¯å¦æ·»åŠ  FullscreenControl
fullscreen = true
#  æ–‡ç« é¡µé¢çš„åˆ†äº«ä¿¡æ¯è®¾ç½®
[params.page.share]
enable = false
Twitter = false
Facebook = false
Linkedin = false
Whatsapp = false
Pinterest = false
Tumblr = false
HackerNews = false
Reddit = false
VK = false
Buffer = false
Xing = false
Line = false
Instapaper = false
Pocket = false
Digg = false
Stumbleupon = false
Flipboard = false
Weibo = false
Renren = false
Myspace = false
Blogger = false
Baidu = false
Odnoklassniki = false
Evernote = false
Skype = false
Trello = false
Mix = false
#  è¯„è®ºç³»ç»Ÿè®¾ç½®
[params.page.comment]
enable = true
# Disqus è¯„è®ºç³»ç»Ÿè®¾ç½®
[params.page.comment.disqus]
#
enable = false
# Disqus çš„ shortnameï¼Œç”¨æ¥åœ¨æ–‡ç« ä¸­å¯ç”¨ Disqus è¯„è®ºç³»ç»Ÿ
shortname = ""
# Gitalk è¯„è®ºç³»ç»Ÿè®¾ç½®
[params.page.comment.gitalk]
#
enable = false
owner = "porrizxx"
repo = "blog-comment"
clientId = "66b49e2a3b34f9346e0a"
clientSecret = "57d6774c3649a8f16b1c130b3d3dded7774b57b8"
proxy = "https://cors-anywhere.azm.workers.dev/https://github.com/login/oauth/access_token"
# Valine è¯„è®ºç³»ç»Ÿè®¾ç½®
[params.page.comment.valine]
enable = false
appId = ""
appKey = ""
placeholder = ""
avatar = "mp"
meta = ""
pageSize = 10
lang = ""
visitor = true
recordIP = true
highlight = true
enableQQ = false
serverURLs = ""
#  emoji æ•°æ®æ–‡ä»¶åç§°, é»˜è®¤æ˜¯ "google.yml"
# ("apple.yml", "google.yml", "facebook.yml", "twitter.yml")
# ä½äº "themes/FixIt/assets/data/emoji/" ç›®å½•
# å¯ä»¥åœ¨ä½ çš„é¡¹ç›®ä¸‹ç›¸åŒè·¯å¾„å­˜æ”¾ä½ è‡ªå·±çš„æ•°æ®æ–‡ä»¶:
# "assets/data/emoji/"
emoji = ""
# Facebook è¯„è®ºç³»ç»Ÿè®¾ç½®
[params.page.comment.facebook]
enable = false
width = "100%"
numPosts = 10
appId = ""
languageCode = "zh_CN"
#  Telegram Comments è¯„è®ºç³»ç»Ÿè®¾ç½®
[params.page.comment.telegram]
enable = false
siteID = ""
limit = 5
height = ""
color = ""
colorful = true
dislikes = false
outlined = false
#  Commento è¯„è®ºç³»ç»Ÿè®¾ç½®
[params.page.comment.commento]
enable = false
#  Utterances è¯„è®ºç³»ç»Ÿè®¾ç½®
[params.page.comment.utterances]
enable = true
# owner/repo
repo = "porrizxx/blog-comment"
issueTerm = "pathname"
label = ""
lightTheme = "github-light"
darkTheme = "github-dark"
#  ç¬¬ä¸‰æ–¹åº“é…ç½®
[params.page.library]
[params.page.library.css]
# someCSS = "some.css"
# ä½äº "assets/"
# æˆ–è€…
# someCSS = "https://cdn.example.com/some.css"
[params.page.library.js]
# someJavascript = "some.js"
# ä½äº "assets/"
# æˆ–è€…
# someJavascript = "https://cdn.example.com/some.js"
#  é¡µé¢ SEO é…ç½®
[params.page.seo]
# å›¾ç‰‡ URL
images = []
# å‡ºç‰ˆè€…ä¿¡æ¯
[params.page.seo.publisher]
name = ""
logoUrl = ""

#  TypeIt é…ç½®
[params.typeit]
# æ¯ä¸€æ­¥çš„æ‰“å­—é€Ÿåº¦ (å•ä½æ˜¯æ¯«ç§’)
speed = 100
# å…‰æ ‡çš„é—ªçƒé€Ÿåº¦ (å•ä½æ˜¯æ¯«ç§’)
cursorSpeed = 1000
# å…‰æ ‡çš„å­—ç¬¦ (æ”¯æŒ HTML æ ¼å¼)
cursorChar = " _"
# æ‰“å­—ç»“æŸä¹‹åå…‰æ ‡çš„æŒç»­æ—¶é—´ (å•ä½æ˜¯æ¯«ç§’, "-1" ä»£è¡¨æ— é™å¤§)
duration = -1
#  æ‰“å­—å®Œæˆåæ˜¯å¦ä¼šè¿ç»­å¾ªç¯
loop = false

#  Mermaid é…ç½®
[params.mermaid]
# å–å€¼è¯¦è§ https://mermaid.js.org/config/theming.html#available-themes
themes = ["default", "dark"]

#  ç›˜å¤ä¹‹ç™½é…ç½®
[params.pangu]
# é€‚ç”¨äºä¸­æ–‡å†™ä½œç”¨æˆ·
enable = false
selector = "article" #

#  æ°´å°é…ç½®
# è¯¦ç»†å‚æ•°è§ https://github.com/Lruihao/watermark#readme
[params.watermark]
enable = false
# æ°´å°å†…å®¹ï¼ˆå…è®¸ HTML æ ¼å¼ï¼‰
content = ""
# æ°´å°é€æ˜åº¦
opacity = 0.1
# æ°´å°çˆ¶èŠ‚ç‚¹
appendTo = ".wrapper>main"
# å•æ°´å°å®½åº¦ å•ä½ï¼špx
width = 150
# å•æ°´å°é«˜åº¦ å•ä½ï¼špx
height = 20
# æ°´å°è¡Œé—´è· å•ä½ï¼špx
rowSpacing = 60
# æ°´å°åˆ—é—´è· å•ä½ï¼špx
colSpacing = 30
# æ°´å°æ—‹è½¬è§’åº¦ å•ä½ï¼šdeg
rotate = 15
# æ°´å°å­—ä½“å¤§å°ï¼Œå•ä½ï¼šrem
fontSize = 0.85
#  æ°´å°å­—ä½“
fontFamily = "inherit"

#  ä¸è’œå­ç»Ÿè®¡
[params.ibruce]
enable = true
# åœ¨æ–‡ç« ä¸­å¼€å¯
enablePost = true

# ç½‘ç«™éªŒè¯ä»£ç ï¼Œç”¨äº Google/Bing/Yandex/Pinterest/Baidu/360/Sogou
[params.verification]
google = ""
bing = ""
yandex = ""
pinterest = ""
baidu = ""
so = ""
sogou = ""

#  ç½‘ç«™ SEO é…ç½®
[params.seo]
# å›¾ç‰‡ URL
image = ""
# ç¼©ç•¥å›¾ URL
thumbnailUrl = ""

#  ç½‘ç«™åˆ†æé…ç½®
[params.analytics]
enable = false
# Google Analytics
[params.analytics.google]
id = ""
# æ˜¯å¦åŒ¿ååŒ–ç”¨æˆ· IP
anonymizeIP = true
# Fathom Analytics
[params.analytics.fathom]
id = ""
# è‡ªè¡Œæ‰˜ç®¡è¿½è¸ªå™¨æ—¶çš„ä¸»æœºè·¯å¾„
server = ""

#  Cookie è®¸å¯é…ç½®
[params.cookieconsent]
enable = true
# ç”¨äº Cookie è®¸å¯æ¨ªå¹…çš„æ–‡æœ¬å­—ç¬¦ä¸²
[params.cookieconsent.content]
message = ""
dismiss = ""
link = ""

#  ç¬¬ä¸‰æ–¹åº“æ–‡ä»¶çš„ CDN è®¾ç½®
[params.cdn]
# CDN æ•°æ®æ–‡ä»¶åç§°, é»˜è®¤ä¸å¯ç”¨
# ("jsdelivr.yml")
# ä½äº "themes/FixIt/assets/data/cdn/" ç›®å½•
# å¯ä»¥åœ¨ä½ çš„é¡¹ç›®ä¸‹ç›¸åŒè·¯å¾„å­˜æ”¾ä½ è‡ªå·±çš„æ•°æ®æ–‡ä»¶:
# "assets/data/cdn/"
data = ""

#  å…¼å®¹æ€§è®¾ç½®
[params.compatibility]
# æ˜¯å¦ä½¿ç”¨ Polyfill.io æ¥å…¼å®¹æ—§å¼æµè§ˆå™¨
polyfill = false
# æ˜¯å¦ä½¿ç”¨ object-fit-images æ¥å…¼å®¹æ—§å¼æµè§ˆå™¨
objectFit = false

#  è¿”å›é¡¶éƒ¨
[params.backToTop]
enable = true
# åœ¨ b2t æŒ‰é’®ä¸­æ˜¾ç¤ºæ»šåŠ¨ç™¾åˆ†æ¯”
scrollpercent = true

#  é˜…è¯»è¿›åº¦æ¡
[params.readingProgress]
enable = true
# å¯ç”¨å€¼ï¼š["left", "right"]
start = "left"
# å¯ç”¨å€¼ï¼š["top", "bottom"]
position = "top"
reversed = false
light = ""
dark = ""
height = "2px"

#  é¡µé¢åŠ è½½æœŸé—´é¡¶éƒ¨çš„è¿›åº¦æ¡
# æœ‰å…³è¯¦ç»†ä¿¡æ¯ï¼šhttps://github.com/CodeByZach/pace
[params.pace]
enable = false
# æ‰€æœ‰å¯ç”¨é¢œè‰²ï¼š
# ["black", "blue", "green", "orange", "pink", "purple", "red", "silver", "white", "yellow"]
color = "blue"
# æ‰€æœ‰å¯ç”¨ä¸»é¢˜ï¼š
# ["barber-shop", "big-counter", "bounce", "center-atom", "center-circle", "center-radar", "center-simple",
# "corner-indicator", "fill-left", "flash", "flat-top", "loading-bar", "mac-osx", "material", "minimal"]
theme = "minimal"

#  å®šä¹‰è‡ªå®šä¹‰æ–‡ä»¶è·¯å¾„
# åœ¨ç«™ç‚¹ç›®å½• `layouts/partials/custom` ä¸­åˆ›å»ºæ‚¨çš„è‡ªå®šä¹‰æ–‡ä»¶ï¼Œå¹¶å–æ¶ˆæ³¨é‡Šä¸‹é¢éœ€è¦çš„æ–‡ä»¶
[params.customFilePath]
# aside = "custom/aside.html"
# profile = "custom/profile.html"
# footer = "custom/footer.html"

#  å¼€å‘è€…é€‰é¡¹
[params.dev]
enable = false
# æ£€æŸ¥æ›´æ–°
c4u = false
# è¯·å‹¿å…¬å¼€å±•ç¤ºï¼
githubToken = ""
# ç§»åŠ¨ç«¯å¼€å‘è€…å·¥å…·é…ç½®
[params.dev.mDevtools]
enable = false
# æ”¯æŒ "vConsole", "eruda"
type = "vConsole"

# Hugo è§£ææ–‡æ¡£çš„é…ç½®
[markup]
# è¯­æ³•é«˜äº®è®¾ç½®
[markup.highlight]
codeFences = true
guessSyntax = true
lineNos = true
lineNumbersInTable = true
# false æ˜¯å¿…è¦çš„è®¾ç½®
# (https://github.com/dillonzq/FixIt/issues/158)
noClasses = false
# Goldmark æ˜¯ Hugo 0.60 ä»¥æ¥çš„é»˜è®¤ Markdown è§£æåº“
[markup.goldmark]
[markup.goldmark.extensions]
definitionList = true
footnote = true
linkify = true
strikethrough = true
table = true
taskList = true
typographer = true
[markup.goldmark.renderer]
# æ˜¯å¦åœ¨æ–‡æ¡£ä¸­ç›´æ¥ä½¿ç”¨ HTML æ ‡ç­¾
unsafe = true
# ç›®å½•è®¾ç½®
[markup.tableOfContents]
startLevel = 1
endLevel = 6

# ä½œè€…é…ç½®
[author]
name = "porrizx"
email = "1119864054@qq.com"
link = "/about/"

# ç½‘ç«™åœ°å›¾é…ç½®
[sitemap]
changefreq = "weekly"
filename = "sitemap.xml"
priority = 0.5

# Permalinks é…ç½®
[Permalinks]
# posts = ":year/:month/:filename"
posts = "/posts/:slug.html"

# éšç§ä¿¡æ¯é…ç½®
[privacy]
#  Google Analytics ç›¸å…³éšç§ (è¢« params.analytics.google æ›¿ä»£)
[privacy.googleAnalytics]
# ...
[privacy.twitter]
enableDNT = true
[privacy.youtube]
privacyEnhanced = true

# ç”¨äºè¾“å‡º Markdown æ ¼å¼æ–‡æ¡£çš„è®¾ç½®
[mediaTypes]
[mediaTypes."text/plain"]
suffixes = ["md"]

# ç”¨äºè¾“å‡º Markdown æ ¼å¼æ–‡æ¡£çš„è®¾ç½®
[outputFormats.MarkDown]
mediaType = "text/plain"
isPlainText = true
isHTML = false

# ç”¨äº Hugo è¾“å‡ºæ–‡æ¡£çš„è®¾ç½®
[outputs]
#
home = ["HTML", "RSS", "JSON"]
page = ["HTML", "MarkDown"]
section = ["HTML", "RSS"]
taxonomy = ["HTML", "RSS"]
taxonomyTerm = ["HTML"]


[menu]
[[menu.main]]
identifier = "posts"
# ä½ å¯ä»¥åœ¨åç§° (å…è®¸ HTML æ ¼å¼) ä¹‹å‰æ·»åŠ å…¶ä»–ä¿¡æ¯, ä¾‹å¦‚å›¾æ ‡
pre = ""
# ä½ å¯ä»¥åœ¨åç§° (å…è®¸ HTML æ ¼å¼) ä¹‹åæ·»åŠ å…¶ä»–ä¿¡æ¯, ä¾‹å¦‚å›¾æ ‡
post = ""
name = "æ–‡ç« "
url = "/posts/"
# å½“ä½ å°†é¼ æ ‡æ‚¬åœåœ¨æ­¤èœå•é“¾æ¥ä¸Šæ—¶, å°†æ˜¾ç¤ºçš„æ ‡é¢˜
title = ""
weight = 1
[[menu.main]]
identifier = "tags"
pre = ""
post = ""
name = "æ ‡ç­¾"
url = "/tags/"
title = ""
weight = 2
[[menu.main]]
identifier = "categories"
pre = ""
post = ""
name = "åˆ†ç±»"
url = "/categories/"
title = ""
weight = 3
[[menu.main]]
identifier = "about"
pre = ""
post = ""
name = "å…³äº"
url = "/about/"
title = ""
weight = 5
